services:
  mongodb:
    image: mongo:7.0
    env_file: .env
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet --username ${MONGO_INITDB_ROOT_USERNAME} --password ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always

volumes:
  mongo_data:
